spring:
  datasource:
    druid:
      maxActive: 10
      initialSize: 2
      minIdle: 2
      driver-class-name: com.mysql.cj.jdbc.Driver
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      filters: stat,slf4j
      maxWait: 60000

mybatis-plus:
  mapper-locations: classpath*:**/mapper/xml/*Mapper.xml

---
spring:
  profiles: test
  datasource:
    druid:
      maxActive: 20
      initialSize: 10
      minIdle: 10
---
spring:
  profiles: prod
  datasource:
    druid:
      maxActive: 50
      initialSize: 20
      minIdle: 20