spring:
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    generator:
      WRITE_NUMBERS_AS_STRINGS: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  main:
    allow-bean-definition-overriding: true
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    elasticsearch:
      enabled: false

# 客户端负载均衡 ribbon参数配置
ribbon:
  ReadTimeout: 10000 # 请求处理的超时时间 毫秒
  ConnectTimeout: 10000  # 请求连接的超时时间 毫秒
  MaxAutoRetries: 2 # 对当前实例的重试次数
  MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
#   hystrix 断路器配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 360000 # 毫秒,断路器超时时间 超过触发熔断,一般配置要大于robbin的超时时间
  threadpool:
    default:
      allowMaximumSizeToDivergeFromCoreSize: true # true 使maximumSize配置生效
      maximumSize: 50 # 默认 maximumSize = coreSize = 10
#eureka配置
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
---
spring:
  profiles: dev
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
app:
  request-proxy-forward:
    enabled: true
---
spring:
  profiles: test
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
---
spring:
  profiles: preprod
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
---
spring:
  profiles: prod
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
#eureka配置
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true